channels:
  - conda-forge
  - r
  - bioconda
dependencies:
  - r-base=3.6
  - rise
  - jupyter_nbextensions_configurator
  - r-tidyverse
  - r-sf
  - r-spdata
  - r-terra
  - r-ggrepel
  - r-rmapshaper
  - r-ggdendro
  - r-tmap
  - r-leaflet
  - r-raster
  - r-gifski
  - r-spdep
  - r-gstat
  - r-mgcv